name: easy_hotel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-374.0.dev <3.0.0'
#  /Users/mac/Documents/flutter/bin
dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  photo_view: ^0.14.0
  flutter_screenutil: ^5.6.0
  get_storage: ^2.0.3
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.1
  url_launcher: ^6.1.7
  dio: ^4.0.6
  internet_connection_checker: ^1.0.0+1
  carousel_slider: ^4.1.1
  http:
  provider:
  shared_preferences: ^2.0.13
  firebase_messaging:
  firebase_core:
  flutter_local_notifications:
  firebase_database:
  flutter_rating_bar: ^4.0.1
  cloud_firestore:
  dotted_border: ^2.0.0+3
  readmore: ^2.1.0
  table_calendar: ^3.0.6
  flutter_staggered_grid_view: ^0.6.2
  google_maps_flutter:
  geolocator:
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.2
  badges: ^2.0.2
  flutter_time_picker_spinner: ^2.0.0
  dropdown_search:
  flutter_expandable_fab : ^1.6.1




dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: karlaBold
      fonts:
        - asset: assets/fonts/Karla-SemiBold.ttf
          weight: 600
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 600
